apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  selector:
    app: front-end  # This should match the deployment's label
  ports:
    - protocol: TCP
      port: 8082       # The port exposed by the service
      targetPort: 8082 # The containerPort in the deployment
      nodePort: 31480  # NodePort to expose externally
  type: NodePort
